#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Mar  7 07:10:39 2012 from "/home/lloyd/python-environments/pyxbee/workspace/Pyxb/src/com/alloydflanagan/usbprobe/USBProbe.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class USBTopFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: USBTopFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.top_panel = wx.Panel(self, -1)
        self.display_panel = wx.Panel(self.top_panel, -1)
        self.selection_panel = wx.Panel(self.top_panel, -1)
        self.selection_splitter = wx.SplitterWindow(self.selection_panel, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.window_1_pane_1_copy = wx.Panel(self.selection_splitter, -1)
        self.window_1_pane_2_copy = wx.Panel(self.selection_splitter, -1)
        self.tree_ctrl_2_copy = wx.TreeCtrl(self.window_1_pane_2_copy, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER)
        self.list_box_1_copy = wx.ListBox(self.window_1_pane_1_copy, -1, choices=[])

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: USBTopFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: USBTopFrame.__do_layout
        top_sizer = wx.BoxSizer(wx.VERTICAL)
        panel_sizer = wx.BoxSizer(wx.VERTICAL)
        device_sizer_copy = wx.GridSizer(3, 3, 0, 0)
        selection_sizer = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6_copy.Add(self.tree_ctrl_2_copy, 1, wx.EXPAND, 0)
        self.window_1_pane_2_copy.SetSizer(sizer_6_copy)
        sizer_5_copy.Add(self.list_box_1_copy, 0, 0, 0)
        self.window_1_pane_1_copy.SetSizer(sizer_5_copy)
        self.selection_splitter.SetSplitMode(wx.SPLIT_VERTICAL)
        self.selection_splitter.Initialize(self.window_1_pane_1_copy)
        selection_sizer.Add(self.selection_splitter, 1, wx.EXPAND, 0)
        self.selection_panel.SetSizer(selection_sizer)
        panel_sizer.Add(self.selection_panel, 1, wx.EXPAND, 0)
        self.display_panel.SetSizer(device_sizer_copy)
        panel_sizer.Add(self.display_panel, 1, wx.EXPAND, 0)
        self.top_panel.SetSizer(panel_sizer)
        top_sizer.Add(self.top_panel, 1, wx.EXPAND, 0)
        self.SetSizer(top_sizer)
        top_sizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class USBTopFrame


class USBProbeMain(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        top_frame = USBTopFrame(None, -1, "")
        self.SetTopWindow(top_frame)
        top_frame.Show()
        return 1

# end of class USBProbeMain

if __name__ == "__main__":
    USBProbe = USBProbeMain(0)
    USBProbe.MainLoop()
