# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Mar  4 12:32:40 2012

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class PyxbMainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PyxbMainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.ButtonsPanel = wx.Panel(self, -1, style=wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.WidgetsPanel = wx.Panel(self, -1)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        self.lRadioList = wx.StaticText(self.WidgetsPanel, -1, "Detected Devices", style=wx.ALIGN_CENTRE)
        self.list_box_1 = wx.ListBox(self.WidgetsPanel, -1, choices=[], style=wx.LB_SINGLE|wx.LB_NEEDED_SB)
        self.SepPanel = wx.Panel(self, -1, style=wx.RAISED_BORDER|wx.TAB_TRAVERSAL)
        self.CommPanel = wx.Panel(self, -1, style=wx.SUNKEN_BORDER|wx.TAB_TRAVERSAL)
        self.CloseButton = wx.Button(self.ButtonsPanel, -1, "button_1")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.CloseApp, self.CloseButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PyxbMainFrame.__set_properties
        self.SetTitle("frame_1")
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = ["frame_1_statusbar"]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.lRadioList.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.list_box_1.SetMinSize((45, 66))
        self.WidgetsPanel.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.SepPanel.SetMinSize((-1, 8))
        self.SepPanel.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.CommPanel.SetBackgroundColour(wx.Colour(216, 216, 191))
        self.CommPanel.SetForegroundColour(wx.Colour(0, 0, 0))
        self.CloseButton.SetBackgroundColour(wx.Colour(159, 191, 255))
        self.CloseButton.SetFont(wx.Font(10, wx.MODERN, wx.NORMAL, wx.BOLD, 0, "Sans"))
        self.ButtonsPanel.SetBackgroundColour(wx.Colour(216, 216, 191))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PyxbMainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        WidgetsSizer = wx.FlexGridSizer(2, 3, 0, 0)
        WidgetsSizer.Add(self.lRadioList, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 4)
        WidgetsSizer.Add(self.list_box_1, 1, wx.EXPAND, 0)
        self.WidgetsPanel.SetSizer(WidgetsSizer)
        sizer_1.Add(self.WidgetsPanel, 0, wx.EXPAND, 0)
        sizer_1.Add(self.SepPanel, 0, wx.ALL|wx.EXPAND, 0)
        sizer_1.Add(self.CommPanel, 1, wx.EXPAND, 0)
        sizer_2.Add(self.CloseButton, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL|wx.SHAPED, 4)
        self.ButtonsPanel.SetSizer(sizer_2)
        sizer_1.Add(self.ButtonsPanel, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def CloseApp(self, event): # wxGlade: PyxbMainFrame.<event_handler>
        print "Event handler `CloseApp' not implemented!"
        event.Skip()

# end of class PyxbMainFrame


